apiVersion: v1
kind: Service
metadata:
  name: springargocd
  labels:
    app: springargocd
spec:
  type: NodePort
  ports:
    - port: 8100
      #protocol: TCP
      targetPort: 8100
      nodePort: 30100
  selector:
    app: springargocd
